# Site settings
title: walksay
email: taodeng0704@gmail.com
description: travel suggestion
baseurl:  /travel/
url: www.walksay.com
github_username:  donkey13

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/travel/page:num/"


collections:
  posts:
    output: true
    permalink: /posts/:path/
  blog:
    output: true
    permalink: /blog/:path/


