# Site settings
title: walksay
email: taodeng0704@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  /travel/
url:  www.walksay.com
twitter_username: twitter_username
github_username:  donkey13

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  travel:
    output: true
    permalink: /travel/:path/
